//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onBoardingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TActividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TActividad()
        {
            this.TDetalleEvaluacions = new HashSet<TDetalleEvaluacion>();
        }
    
        public int IdActividad { get; set; }
        public string NombreActividad { get; set; }
        public string DescripcionActividad { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> DiasEvaluar { get; set; }
        public Nullable<int> IdObjetivo { get; set; }
        public string UsuarioInserto { get; set; }
        public Nullable<System.DateTime> FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual TObjetivo TObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDetalleEvaluacion> TDetalleEvaluacions { get; set; }
    }
}
