//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onBoardingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPlanOnBoarding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPlanOnBoarding()
        {
            this.TDetalleEvaluacions = new HashSet<TDetalleEvaluacion>();
        }
    
        public int IdPlanOnBoarding { get; set; }
        public string NombreTipo { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<bool> Realizado { get; set; }
        public Nullable<int> PuntuacionTotal { get; set; }
        public Nullable<int> EscalaTC { get; set; }
        public Nullable<decimal> Puntuacion { get; set; }
        public Nullable<decimal> ResultadoFinal { get; set; }
        public Nullable<int> EscalaWill { get; set; }
        public Nullable<int> EscalaSkill { get; set; }
        public string Cuadrante { get; set; }
        public Nullable<int> NumeroEvaluacion { get; set; }
        public string UsuarioInserto { get; set; }
        public Nullable<System.DateTime> FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual TColaborador TColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDetalleEvaluacion> TDetalleEvaluacions { get; set; }
        public virtual TPuesto TPuesto { get; set; }
    }
}
